# -*- coding: utf-8 -*-
"""
/***************************************************************************
 mod_layer
                                 A QGIS plugin
 
This plugin builds 3d models of layers.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-11
        copyright            : (C) 2025 by DF
        email                : dfgktf@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load mod_layer class from file mod_layer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .mod_layer import mod_layer
    return mod_layer(iface)
