# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/goncarovaevgenia/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/mod_layer/mod_layer_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mod_layer_dialog_base(object):
    def setupUi(self, mod_layer_dialog_base):
        mod_layer_dialog_base.setObjectName("mod_layer_dialog_base")
        mod_layer_dialog_base.resize(400, 390)
        mod_layer_dialog_base.setMinimumSize(QtCore.QSize(400, 390))
        mod_layer_dialog_base.setMaximumSize(QtCore.QSize(400, 390))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        mod_layer_dialog_base.setFont(font)
        self.button_box = QtWidgets.QDialogButtonBox(mod_layer_dialog_base)
        self.button_box.setGeometry(QtCore.QRect(40, 350, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.listWidget = QtWidgets.QListWidget(mod_layer_dialog_base)
        self.listWidget.setGeometry(QtCore.QRect(20, 150, 361, 191))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.label = QtWidgets.QLabel(mod_layer_dialog_base)
        self.label.setGeometry(QtCore.QRect(20, 20, 361, 121))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(mod_layer_dialog_base)
        self.label_2.setGeometry(QtCore.QRect(30, 150, 60, 16))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(mod_layer_dialog_base)
        self.button_box.accepted.connect(mod_layer_dialog_base.accept) # type: ignore
        self.button_box.rejected.connect(mod_layer_dialog_base.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(mod_layer_dialog_base)

    def retranslateUi(self, mod_layer_dialog_base):
        _translate = QtCore.QCoreApplication.translate
        mod_layer_dialog_base.setWindowTitle(_translate("mod_layer_dialog_base", "Выбор слоёв"))
        self.label.setText(_translate("mod_layer_dialog_base", "Для того, чтобы плагин работал корректно, необходимо\n"
"соблюдение слоями следующих условий:\n"
"1.  На слое присутствуют только точки.\n"
"2.  У всех объектов слоя c двухмерными точками, \n"
"       не имеющими третьей координаты, \n"
"       есть атрибут «height»(высота/глубина).\n"
"3. Количество слоёв ≤ 8"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mod_layer_dialog_base = QtWidgets.QDialog()
    ui = Ui_mod_layer_dialog_base()
    ui.setupUi(mod_layer_dialog_base)
    mod_layer_dialog_base.show()
    sys.exit(app.exec_())
