# -*- coding: utf-8 -*-
"""
/***************************************************************************
 mod_layerDialog
                                 A QGIS plugin
 
This plugin builds 3d models of layers.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-11
        git sha              : $Format:%H$
        copyright            : (C) 2025 by DF
        email                : dfgktf@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt import QtWidgets, uic

class mod_layerDialog(QtWidgets.QDialog):
    def __init__(self, parent=None):
        super(mod_layerDialog, self).__init__(parent)
        # Load UI from a .ui file (you need to create this UI file)
        uic.loadUi('path/to/your/dialog.ui', self)

        # Access UI elements by their object names defined in Qt Designer
        self.pointSizeSpinBox = self.findChild(QtWidgets.QSpinBox, 'pointSizeSpinBox')
        self.filePathLineEdit = self.findChild(QtWidgets.QLineEdit, 'filePathLineEdit')
        self.browseButton = self.findChild(QtWidgets.QPushButton, 'browseButton')

        # Connect browse button to a file dialog
        self.browseButton.clicked.connect(self.browse_file)

    def browse_file(self):
        """Open a file dialog to select a file."""
        options = QtWidgets.QFileDialog.Options()
        file_path, _ = QtWidgets.QFileDialog.getOpenFileName(self, "Select Elevation File", "", "All Files (*);;CSV Files (*.csv)", options=options)
        if file_path:
            self.filePathLineEdit.setText(file_path)
